baseurl: "/jekyll-test2" # the subpath of your site, e.g. /blog
url: "rjduran.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"    